
mat_aluminium.set('family', 'aluminum');
mat_aluminium.propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
mat_aluminium.propertyGroup('def').descr('relpermeability_symmetry', '');
mat_aluminium.propertyGroup('def').set('heatcapacity', '900[J/(kg*K)]');
mat_aluminium.propertyGroup('def').descr('heatcapacity_symmetry', '');
mat_aluminium.propertyGroup('def').set('thermalconductivity', {'238[W/(m*K)]' '0' '0' '0' '238[W/(m*K)]' '0' '0' '0' '238[W/(m*K)]'});
mat_aluminium.propertyGroup('def').descr('thermalconductivity_symmetry', '');
mat_aluminium.propertyGroup('def').set('electricconductivity', {'3.774e7[S/m]' '0' '0' '0' '3.774e7[S/m]' '0' '0' '0' '3.774e7[S/m]'});
mat_aluminium.propertyGroup('def').descr('electricconductivity_symmetry', '');
mat_aluminium.propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
mat_aluminium.propertyGroup('def').descr('relpermittivity_symmetry', '');
mat_aluminium.propertyGroup('def').set('thermalexpansioncoefficient', {'23e-6[1/K]' '0' '0' '0' '23e-6[1/K]' '0' '0' '0' '23e-6[1/K]'});
mat_aluminium.propertyGroup('def').descr('thermalexpansioncoefficient_symmetry', '');
mat_aluminium.propertyGroup('def').set('density', '2700[kg/m^3]');
mat_aluminium.propertyGroup('def').descr('density_symmetry', '');
mat_aluminium.propertyGroup.create('Enu', 'Young''s modulus and Poisson''s ratio');
mat_aluminium.propertyGroup('Enu').set('youngsmodulus', '70e9[Pa]');
mat_aluminium.propertyGroup('Enu').descr('youngsmodulus_symmetry', '');
mat_aluminium.propertyGroup('Enu').set('poissonsratio', '0.33');
mat_aluminium.propertyGroup('Enu').descr('poissonsratio_symmetry', '');
mat_aluminium.propertyGroup('Enu').info('category').title([]);
mat_aluminium.propertyGroup('Enu').info('category').body('Solid_mechanics/Linear_elastic_material');
mat_aluminium.propertyGroup.create('Murnaghan', 'Murnaghan');
mat_aluminium.propertyGroup('Murnaghan').set('l', '');
mat_aluminium.propertyGroup('Murnaghan').set('m', '');
mat_aluminium.propertyGroup('Murnaghan').set('n', '');
mat_aluminium.propertyGroup('Murnaghan').set('l', '');
mat_aluminium.propertyGroup('Murnaghan').set('m', '');
mat_aluminium.propertyGroup('Murnaghan').set('n', '');
mat_aluminium.propertyGroup('Murnaghan').set('l', '');
mat_aluminium.propertyGroup('Murnaghan').set('m', '');
mat_aluminium.propertyGroup('Murnaghan').set('n', '');
mat_aluminium.propertyGroup('Murnaghan').set('l', '-2.5e11[Pa]');
mat_aluminium.propertyGroup('Murnaghan').set('m', '-3.3e11[Pa]');
mat_aluminium.propertyGroup('Murnaghan').set('n', '-3.5e11[Pa]');
mat_aluminium.propertyGroup('Murnaghan').descr('l_symmetry', '');
mat_aluminium.propertyGroup('Murnaghan').descr('m_symmetry', '');
mat_aluminium.propertyGroup('Murnaghan').descr('n_symmetry', '');
mat_aluminium.propertyGroup('Murnaghan').info('category').title([]);
mat_aluminium.propertyGroup('Murnaghan').info('category').body('Solid_mechanics/Hyperelastic_material');
mat_aluminium.propertyGroup.create('Lame', ['Lam' native2unicode(hex2dec({'00' 'e9'}), 'unicode') ' parameters']);
mat_aluminium.propertyGroup('Lame').set('lambLame', '');
mat_aluminium.propertyGroup('Lame').set('muLame', '');
mat_aluminium.propertyGroup('Lame').set('lambLame', '');
mat_aluminium.propertyGroup('Lame').set('muLame', '');
mat_aluminium.propertyGroup('Lame').set('lambLame', '');
mat_aluminium.propertyGroup('Lame').set('muLame', '');
mat_aluminium.propertyGroup('Lame').set('lambLame', '5.1e10[Pa]');
mat_aluminium.propertyGroup('Lame').set('muLame', '2.6e10[Pa]');
mat_aluminium.propertyGroup('Lame').descr('lambLame_symmetry', '');
mat_aluminium.propertyGroup('Lame').descr('muLame_symmetry', '');
mat_aluminium.propertyGroup('Lame').info('category').title([]);
mat_aluminium.propertyGroup('Lame').info('category').body('Solid_mechanics/Linear_elastic_material');